TEXT_FROM_A = "text_a.txt"
TEXT_FROM_B = "text_b.txt"
RESULT_TEXT = "text_result.txt"
TICKER_O = "OPTIONS#"
TICKER_F = "FUTURES#"
TICKER_S = "STOCKS#"
EXCEPTION_U = "Unexpected result."
SEPARATOR = "."